# Slicing ile Elemanlara Erismek (Array alt kümesine olusmak)

In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)

In [3]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[0:3]

array([20, 21, 22])

# iki boyutlu slice islemleri

In [7]:
m = np.random.randint(10, size=(5,5))
m

array([[0, 4, 3, 3, 1],
       [0, 9, 8, 8, 0],
       [5, 6, 6, 8, 2],
       [8, 5, 7, 1, 9],
       [7, 2, 5, 2, 1]])

In [8]:
m[:,0]

array([0, 0, 5, 8, 7])

In [9]:
m[:,1]

array([4, 9, 6, 5, 2])

In [10]:
m[2,:]

array([5, 6, 6, 8, 2])

In [11]:
m[0:2, 0:3]

array([[0, 4, 3],
       [0, 9, 8]])

In [13]:
m

array([[0, 4, 3, 3, 1],
       [0, 9, 8, 8, 0],
       [5, 6, 6, 8, 2],
       [8, 5, 7, 1, 9],
       [7, 2, 5, 2, 1]])

In [12]:
m[::, :2]

array([[0, 4],
       [0, 9],
       [5, 6],
       [8, 5],
       [7, 2]])

In [14]:
m[1:3, 0:2]

array([[0, 9],
       [5, 6]])