# Array SIRALAMA(sorting)

In [1]:
import numpy as np

In [2]:
v = np.array([2,1,4,3,5])

In [4]:
np.sort(v)

array([1, 2, 3, 4, 5])

* burada orjinal dizin bozulur, usttekinde bozulmaz

In [5]:
v.sort()

In [6]:
v

array([1, 2, 3, 4, 5])

# iki boyutlu array siralama

In [7]:
m = np.random.normal(20,4, (3,3))

In [8]:
m

array([[28.15620701, 19.35328078, 17.44563662],
       [22.73887351, 16.75267186, 17.69934751],
       [23.2184076 , 18.4506854 , 19.67712253]])

In [9]:
np.sort(m, axis=1)

array([[17.44563662, 19.35328078, 28.15620701],
       [16.75267186, 17.69934751, 22.73887351],
       [18.4506854 , 19.67712253, 23.2184076 ]])

In [10]:
np.sort(m, axis=0)

array([[22.73887351, 16.75267186, 17.44563662],
       [23.2184076 , 18.4506854 , 17.69934751],
       [28.15620701, 19.35328078, 19.67712253]])