# NUMPY ARRAY OLUSTURMAK

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
a=np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [8]:
np.array([3.14, 4,2,13] , dtype="int")

array([ 3,  4,  2, 13])

## Sifirdan array olusturma

In [11]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5), 3, dtype=int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [15]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [18]:
np.random.normal(10,4, (3,4))

array([[12.21130538,  8.38300084, 10.53252219,  8.27203436],
       [ 9.14940703, 10.31417758,  4.82985383,  9.02016486],
       [11.66468357,  5.90559397, 18.63473762, 12.68856107]])

In [19]:
np.random.randint(0,10,(3,3))

array([[9, 7, 2],
       [3, 1, 6],
       [6, 0, 9]])