# YENIDEN SEKILLENDIRME (reshaping)

In [1]:
import numpy as np

In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a=np.arange(1,10)

In [9]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a.ndim

1

In [14]:
b=a.reshape((1,9))

In [16]:
b.ndim

2