# Fancy Index ile Elemanlara erismek

In [1]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [2]:
v[1]

3

In [3]:
al_getir=[1,3,5]
v[al_getir]

array([ 3,  9, 15])

## iki boyutta fancy

In [4]:
 m = np.arange(9).reshape((3,3))

In [5]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [7]:
m[satir, sutun]

array([1, 5])

## basit index ile fancy index

In [8]:
m[0, [1,2]]

array([1, 2])

In [9]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## slice ile fancy

In [10]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])