# Kosullu eleman islemleri

In [1]:
import numpy as np
v = np.array([1,2,3,4,5])

In [3]:
v > 3

array([False, False, False,  True,  True])

In [4]:
v[v<3]

array([1, 2])

In [5]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [6]:
v * 5

array([ 5, 10, 15, 20, 25])